{{- if .Values.mariadb.auth.createSecrets }}
{{- $dbPassword := randAlphaNum 10 | nospace -}}
{{- $adminPassword := randAlphaNum 10 | nospace -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadb.auth.existingSecret }}
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  ADMIN_PASSWORD: {{ $adminPassword | b64enc | quote }}
  SECRET: {{ randAlphaNum 10 | b64enc | quote }}
  KEY: {{ randAlphaNum 10 | b64enc | quote }}
  mariadb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mariadb-password: {{ $dbPassword | b64enc | quote }}
  mariadb-replication-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}