apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "directus.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
data:
  DB_CLIENT: "mysql"
  DB_HOST: {{- if .Values.mariadb.enableInstallation }} 
    {{- if .Values.mariadb.mariadbURL }} 
      "{{ .Values.mariadb.mariadbURL }}" 
    {{- else }} 
      "{{ .Release.Name }}-mariadb.{{ .Release.Namespace }}.svc.cluster.local" 
    {{- end }}
  {{- else if .Values.postgresql.enableInstallation }} 
    {{- if .Values.postgresql.postgresqlURL }} 
      "{{ .Values.postgresql.postgresqlURL }}" 
    {{- else }} 
      "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local" 
    {{- end }}
  {{- end }}
  DB_PORT: {{- if .Values.mariadb.enableInstallation }} 
      "3306" 
    {{- else if .Values.postgresql.enableInstallation }} 
      "5432" 
    {{- end }}
  DB_DATABASE: {{- if .Values.mariadb.enableInstallation }} 
    "{{ .Values.mariadb.auth.database }}" 
  {{- else if .Values.postgresql.enableInstallation }} 
    "{{ .Values.postgresql.auth.database }}" 
  {{- end }}
  DB_USER: {{- if .Values.mariadb.enableInstallation }} 
    "{{ .Values.mariadb.auth.username }}" 
  {{- else if .Values.postgresql.enableInstallation }} 
    "{{ .Values.postgresql.auth.username }}" 
  {{- end }}
  ADMIN_EMAIL: "{{ .Values.adminEmail }}"
  REDIS_ENABLED: {{- if .Values.redis.enabled }} "true" {{- else }} "false" {{- end }}
  {{- if .Values.redis.enabled}}
  REDIS_HOST: {{ .Release.Name }}-redis-master
  REDIS_PORT: "6379"
  REDIS_USERNAME: "default"
  {{- end}}
